/**
 ** Name: Types redux
 ** Author: DTP-Education
 ** CreatedAt: 2021
 ** Description: Description of Types.js
 **/

/** COMMON */
export const CHANGE_CONNECTION_STATUS = '[COMMON] CHANGE_CONNECTION_STATUS';
export const CHANGE_LANGUAGE = '[COMMON] CHANGE_LANGUAGE';
export const CHANGE_FORMAT_DATE = '[COMMON] CHANGE_FORMAT_DATE';
export const CHANGE_FORMAT_DATE_VIEW = '[COMMON] CHANGE_FORMAT_DATE_VIEW';
export const CHANGE_FORMAT_DATE_CUSTOM1 = '[COMMON] CHANGE_FORMAT_DATE_CUSTOM1';
export const CHANGE_PER_PAGE = '[COMMON] CHANGE_PER_PAGE';
export const CHANGE_IS_SEARCH = '[COMMON] CHANGE_IS_SEARCH';

/** AUTH */
export const LOGOUT = '[AUTH] LOGOUT';
export const START_LOGIN = '[AUTH] START_LOGIN';
export const SUCCESS_LOGIN = '[AUTH] SUCCESS_LOGIN';
export const ERROR_LOGIN = '[AUTH] ERROR_LOGIN';
export const START_REFRESH_TOKEN = '[AUTH] START_REFRESH_TOKEN';
export const SUCCESS_REFRESH_TOKEN = '[AUTH] SUCCESS_REFRESH_TOKEN';
export const ERROR_REFRESH_TOKEN = '[AUTH] ERROR_REFRESH_TOKEN';
export const START_CHANGE_PASSWORD = '[AUTH] START_CHANGE_PASSWORD';
export const SUCCESS_CHANGE_PASSWORD = '[AUTH] SUCCESS_CHANGE_PASSWORD';
export const ERROR_CHANGE_PASSWORD = '[AUTH] ERROR_CHANGE_PASSWORD';

export const START_FORGOT_PASSWORD = '[AUTH] START_FORGOT_PASSWORD';
export const SUCCESS_FORGOT_PASSWORD = '[AUTH] SUCCESS_FORGOT_PASSWORD';
export const ERROR_FORGOT_PASSWORD = '[AUTH] ERROR_FORGOT_PASSWORD';

export const START_UPDATE_PASSWORD = '[AUTH] START_UPDATE_PASSWORD';
export const SUCCESS_UPDATE_PASSWORD = '[AUTH] SUCCESS_UPDATE_PASSWORD';
export const ERROR_UPDATE_PASSWORD = '[AUTH] ERROR_UPDATE_PASSWORD';

export const RESET_CHECK_TOKEN_PASSWORD = '[AUTH] RESET_CHECK_TOKEN_PASSWORD';
export const START_CHECK_TOKEN_PASSWORD = '[AUTH] START_CHECK_TOKEN_PASSWORD';
export const SUCCESS_CHECK_TOKEN_PASSWORD =
  '[AUTH] SUCCESS_CHECK_TOKEN_PASSWORD';
export const ERROR_CHECK_TOKEN_PASSWORD = '[AUTH] ERROR_CHECK_TOKEN_PASSWORD';

/** MASTER DATA */
export const RESET_STATUS_MASTER_DATA = '[MASTER] RESET_STATUS_MASTER_DATA';
export const START_FETCH_MASTER_DATA = '[MASTER] START_FETCH_MASTER_DATA';
export const ERROR_FETCH_MASTER_DATA = '[MASTER] ERROR_FETCH_MASTER_DATA';
export const START_FETCH_ASSET_BY_USER = '[MASTER] START_FETCH_ASSET_BY_USER';
export const ERROR_FETCH_ASSET_BY_USER = '[MASTER] ERROR_FETCH_ASSET_BY_USER';
export const CHANGE_MASTER_ALL = '[MASTER] CHANGE_MASTER_ALL';
export const CHANGE_MASTER_REGIONS = '[MASTER] CHANGE_MASTER_REGIONS';
export const CHANGE_MASTER_DEPARTMENT = '[MASTER] CHANGE_MASTER_DEPARTMENT';
export const CHANGE_MASTER_EMPLOYEES = '[MASTER] CHANGE_MASTER_EMPLOYEES';
export const CHANGE_MASTER_SUPPLIERS = '[MASTER] CHANGE_MASTER_SUPPLIERS';
export const CHANGE_MASTER_COMPANYS = '[MASTER] CHANGE_MASTER_COMPANYS';
export const CHANGE_MASTER_ASSETSTYPE = '[MASTER] CHANGE_MASTER_ASSETSTYPE';
export const CHANGE_MASTER_ASSETSGROUP = '[MASTER] CHANGE_MASTER_ASSETSGROUP';
export const CHANGE_MASTER_ASSETSGROUPDETAIL =
  '[MASTER] CHANGE_MASTER_ASSETSGROUPDETAIL';
export const CHANGE_MASTER_ASSET_BY_USER =
  '[MASTER] CHANGE_MASTER_ASSET_BY_USER';

/** APPROVED ASSETS */
export const RESET_REQUEST_APPROVED = '[APPROVED] RESET_REQUEST_APPROVED';
export const START_FETCH_LIST_REQUEST_APPROVED =
  '[APPROVED] START_FETCH_LIST_REQUEST_APPROVED';
export const SUCCESS_FETCH_LIST_REQUEST_APPROVED =
  '[APPROVED] SUCCESS_FETCH_LIST_REQUEST_APPROVED';
export const ERROR_FETCH_LIST_REQUEST_APPROVED =
  '[APPROVED] ERROR_FETCH_LIST_REQUEST_APPROVED';
export const START_FETCH_REQUEST_DETAIL = '[TASK] START_FETCH_REQUEST_DETAIL';
export const SUCCESS_FETCH_REQUEST_DETAIL =
  '[TASK] SUCCESS_FETCH_REQUEST_DETAIL';
export const ERROR_FETCH_REQUEST_DETAIL = '[TASK] ERROR_FETCH_REQUEST_DETAIL';
export const START_FETCH_ADD_REQUEST_APPROVED =
  '[APPROVED] START_FETCH_ADD_REQUEST_APPROVED';
export const SUCCESS_FETCH_ADD_REQUEST_APPROVED =
  '[APPROVED] SUCCESS_FETCH_ADD_REQUEST_APPROVED';
export const ERROR_FETCH_ADD_REQUEST_APPROVED =
  '[APPROVED] ERROR_FETCH_ADD_REQUEST_APPROVED';
export const START_FETCH_APPROVED_REQUEST =
  '[APPROVED] START_FETCH_APPROVED_REQUEST';
export const SUCCESS_FETCH_APPROVED_REQUEST =
  '[APPROVED] SUCCESS_FETCH_APPROVED_REQUEST';
export const ERROR_FETCH_APPROVED_REQUEST =
  '[APPROVED] ERROR_FETCH_APPROVED_REQUEST';
export const START_FETCH_REJECT_REQUEST =
  '[APPROVED] START_FETCH_REJECT_REQUEST';
export const SUCCESS_FETCH_REJECT_REQUEST =
  '[APPROVED] SUCCESS_FETCH_REJECT_REQUEST';
export const ERROR_FETCH_REJECT_REQUEST =
  '[APPROVED] ERROR_FETCH_REJECT_REQUEST';

/** APPROVED DAMAGED NAD DAMAGE */
export const RESET_REQUEST_DAMAGE = '[APPROVED] RESET_REQUEST_DAMAGE';
export const RESET_REQUEST_LOST = '[APPROVED] RESET_REQUEST_LOST';
export const START_FETCH_LIST_REQUEST_DAMAGE =
  '[APPROVED] START_FETCH_LIST_REQUEST_DAMAGE';
export const SUCCESS_FETCH_LIST_REQUEST_DAMAGE =
  '[APPROVED] SUCCESS_FETCH_LIST_REQUEST_DAMAGE';
export const ERROR_FETCH_LIST_REQUEST_DAMAGE =
  '[APPROVED] ERROR_FETCH_LIST_REQUEST_DAMAGE';
export const START_FETCH_LIST_REQUEST_LOST =
  '[APPROVED] START_FETCH_LIST_REQUEST_LOST';
export const SUCCESS_FETCH_LIST_REQUEST_LOST =
  '[APPROVED] SUCCESS_FETCH_LIST_REQUEST_LOST';
export const ERROR_FETCH_LIST_REQUEST_LOST =
  '[APPROVED] ERROR_FETCH_LIST_REQUEST_LOST';
export const START_FETCH_ADD_REQUEST_LOST =
  '[APPROVED] START_FETCH_ADD_REQUEST_LOST';
export const SUCCESS_FETCH_ADD_REQUEST_LOST =
  '[APPROVED] SUCCESS_FETCH_ADD_REQUEST_LOST';
export const ERROR_FETCH_ADD_REQUEST_LOST =
  '[APPROVED] ERROR_FETCH_ADD_REQUEST_LOST';
export const START_FETCH_APPROVED_LOST = '[APPROVED] START_FETCH_APPROVED_LOST';
export const SUCCESS_FETCH_APPROVED_LOST =
  '[APPROVED] SUCCESS_FETCH_APPROVED_LOST';
export const ERROR_FETCH_APPROVED_LOST = '[APPROVED] ERROR_FETCH_APPROVED_LOST';
export const START_FETCH_REJECT_LOST = '[APPROVED] START_FETCH_REJECT_LOST';
export const SUCCESS_FETCH_REJECT_LOST = '[APPROVED] SUCCESS_FETCH_REJECT_LOST';
export const ERROR_FETCH_REJECT_LOST = '[APPROVED] ERROR_FETCH_REJECT_LOST';

/** PROJECT MANAGEMENT */
export const START_FETCH_LIST_PROJECT = '[PROJECT] START_FETCH_LIST_PROJECT';
export const SUCCESS_FETCH_LIST_PROJECT =
  '[PROJECT] SUCCESS_FETCH_LIST_PROJECT';
export const ERROR_FETCH_LIST_PROJECT = '[PROJECT] ERROR_FETCH_LIST_PROJECT';

/** TASK MANAGEMENT */
export const START_FETCH_LIST_TASK = '[TASK] START_FETCH_LIST_TASK';
export const SUCCESS_FETCH_LIST_TASK = '[TASK] SUCCESS_FETCH_LIST_TASK';
export const ERROR_FETCH_LIST_TASK = '[TASK] ERROR_FETCH_LIST_TASK';

export const START_FETCH_TASK_DETAIL = '[TASK] START_FETCH_TASK_DETAIL';
export const SUCCESS_FETCH_TASK_DETAIL = '[TASK] SUCCESS_FETCH_TASK_DETAIL';
export const ERROR_FETCH_TASK_DETAIL = '[TASK] ERROR_FETCH_TASK_DETAIL';

export const START_FETCH_TASK_COMMENT = '[TASK] START_FETCH_TASK_COMMENT';
export const SUCCESS_FETCH_TASK_COMMENT = '[TASK] SUCCESS_FETCH_TASK_COMMENT';
export const ERROR_FETCH_TASK_COMMENT = '[TASK] ERROR_FETCH_TASK_COMMENT';

export const START_FETCH_TASK_WATCHERS = '[TASK] START_FETCH_TASK_WATCHERS';
export const SUCCESS_FETCH_TASK_WATCHERS = '[TASK] SUCCESS_FETCH_TASK_WATCHERS';
export const ERROR_FETCH_TASK_WATCHERS = '[TASK] ERROR_FETCH_TASK_WATCHERS';

export const START_FETCH_TASK_UPDATE = '[TASK] START_FETCH_TASK_UPDATE';
export const SUCCESS_FETCH_TASK_UPDATE = '[TASK] SUCCESS_FETCH_TASK_UPDATE';
export const ERROR_FETCH_TASK_UPDATE = '[TASK] ERROR_FETCH_TASK_UPDATE';

/** PROJECT OVERVIEW */
export const START_FETCH_PROJECT_OVERVIEW =
  '[OVERVIEW] START_FETCH_PROJECT_OVERVIEW';
export const SUCCESS_FETCH_PROJECT_OVERVIEW =
  '[OVERVIEW] SUCCESS_FETCH_PROJECT_OVERVIEW';
export const ERROR_FETCH_PROJECT_OVERVIEW =
  '[OVERVIEW] ERROR_FETCH_PROJECT_OVERVIEW';

/** BOOKING */
export const RESET_REQUEST_BOOKING = '[BOOKING] RESET_REQUEST_BOOKING';
export const RESET_BOOKING_DETAIL = '[BOOKING] RESET_BOOKING_DETAIL';

export const START_FETCH_LIST_BOOKING = '[BOOKING] START_FETCH_LIST_BOOKING';
export const SUCCESS_FETCH_LIST_BOOKING =
  '[BOOKING] SUCCESS_FETCH_LIST_BOOKING';
export const ERROR_FETCH_LIST_BOOKING = '[BOOKING] ERROR_FETCH_LIST_BOOKING';

export const START_FETCH_ADD_BOOKING = '[BOOKING] START_FETCH_ADD_BOOKING';
export const SUCCESS_FETCH_ADD_BOOKING = '[BOOKING] SUCCESS_FETCH_ADD_BOOKING';
export const ERROR_FETCH_ADD_BOOKING = '[BOOKING] ERROR_FETCH_ADD_BOOKING';

export const START_FETCH_REMOVE_BOOKING =
  '[BOOKING] START_FETCH_REMOVE_BOOKING';
export const SUCCESS_FETCH_REMOVE_BOOKING =
  '[BOOKING] SUCCESS_FETCH_REMOVE_BOOKING';
export const ERROR_FETCH_REMOVE_BOOKING =
  '[BOOKING] ERROR_FETCH_REMOVE_BOOKING';

export const START_FETCH_BOOKING_DETAIL =
  '[BOOKING] START_FETCH_BOOKING_DETAIL';
export const SUCCESS_FETCH_BOOKING_DETAIL =
  '[BOOKING] SUCCESS_FETCH_BOOKING_DETAIL';
export const ERROR_FETCH_BOOKING_DETAIL =
  '[BOOKING] ERROR_FETCH_BOOKING_DETAIL';

export const START_FETCH_LIST_BOOKING_BY_RESRC =
  '[BOOKING] START_FETCH_LIST_BOOKING_BY_RESRC';
export const SUCCESS_FETCH_LIST_BOOKING_BY_RESRC =
  '[BOOKING] SUCCESS_FETCH_LIST_BOOKING_BY_RESRC';
export const ERROR_FETCH_LIST_BOOKING_BY_RESRC =
  '[BOOKING] ERROR_FETCH_LIST_BOOKING_BY_RESRC';
