/**
 ** Name: Types.js
 ** Author: 
 ** CreatedAt: 2021
 ** Description: Description of Types.js
 **/
/** CONNECTION */
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
/** LANG */
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
/** MASTER DATA */
export const CHANGE_MASTER_ALL = 'CHANGE_MASTER_ALL';
export const CHANGE_MASTER_REGIONS = 'CHANGE_MASTER_REGIONS';
export const CHANGE_MASTER_DEPARTMENT = 'CHANGE_MASTER_DEPARTMENT';
export const CHANGE_MASTER_EMPLOYEES = 'CHANGE_MASTER_EMPLOYEES';
export const CHANGE_MASTER_SUPPLIERS = 'CHANGE_MASTER_SUPPLIERS';
export const CHANGE_MASTER_COMPANYS = 'CHANGE_MASTER_COMPANYS';
export const CHANGE_MASTER_ASSETSTYPE = 'CHANGE_MASTER_ASSETSTYPE';
export const CHANGE_MASTER_ASSETSGROUP = 'CHANGE_MASTER_ASSETSGROUP';
export const CHANGE_MASTER_ASSETSGROUPDETAIL = 'CHANGE_MASTER_ASSETSGROUPDETAIL';
